# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: firstjob
    steps:
    - script: echo Hello, world!
  - job: secondjob
    steps:
    - script: echo Qa Deploy
- stage: DevDeploy
  dependsOn: build
  jobs:
  - job: devjob
    steps:
    - script: echo dev Deploy
- stage: QADeploy
  dependsOn: 
  - build
  - DevDeploy 
  jobs:
  - job: QAjob
    steps:
    - script: echo Qa Deploy

